apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  serviceAccountName: flux-operator
  interval: 12h
  retryInterval: 3m
  path: ./tenants
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-env
      - kind: ConfigMap
        name: flux-runtime-info
  patches:
    - patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
      target:
        labelSelector: resourceset.fluxcd.controlplane.io/name=infra-github
    - patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
      target:
        labelSelector: app.kubernetes.io/part-of=github
    - patch: |
        $patch: delete
        apiVersion: all.toolkit.fluxcd.io/v1
        kind: all
        metadata:
          name: all
      target:
        labelSelector: resourceset.fluxcd.controlplane.io/name=infra-gitlab
    - patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
      target:
        labelSelector: app.kubernetes.io/part-of=gitlab
    - patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
      target:
        labelSelector: resourceset.fluxcd.controlplane.io/name=infra-tailscale
    - patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
      target:
        labelSelector: app.kubernetes.io/part-of=tailscale
