apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  serviceAccountName: flux-operator
  interval: 12h
  retryInterval: 3m
  path: ./tenants
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-env
      - kind: ConfigMap
        name: flux-runtime-info
  patches:
    - target:
        kind: ResourceSet
        name: infra-(github|gitlab|tailscale)
        # labelSelector: "app.kubernetes.io/part-of=flux"
      patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
