apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-tenant
  namespace: flux-system
spec:
  serviceAccountName: flux-operator
  interval: 12h
  retryInterval: 3m
  path: ./tenants/apps
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
