apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infra
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: policies
      namespace: flux-system
      ready: true
      readyExpr: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    # - apiVersion: fluxcd.controlplane.io/v1
    #   kind: ResourceSet
    #   name: infra-ccm
    #   namespace: flux-system
    #   ready: true
    #   readyExpr: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: infra-external-secrets
      namespace: flux-system
      ready: true
      readyExpr: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  inputs:
    - tenant: cert-manager
      configs: true
      tag: "${ARTIFACT_TAG}"
      environment: "${ENVIRONMENT}"
      artifactSubjectWorkflow: "${ARTIFACT_SUBJECT_WORKFLOW}"
      artifactSubjectGitRef: "${ARTIFACT_SUBJECT_GIT_REF}"
    - tenant: cilium # network
      namespace: kube-system
      configs: true
      tag: "${ARTIFACT_TAG}"
      environment: "${ENVIRONMENT}"
      artifactSubjectWorkflow: "${ARTIFACT_SUBJECT_WORKFLOW}"
      artifactSubjectGitRef: "${ARTIFACT_SUBJECT_GIT_REF}"
      # TODO: cni: "${CNI}"
    # - tenant: flux-operator
    #   namespace: flux-system
    #   tag: "${ARTIFACT_TAG}"
    #   environment: "${ENVIRONMENT}"
    #   artifactSubjectWorkflow: "${ARTIFACT_SUBJECT_WORKFLOW}"
    #   artifactSubjectGitRef: "${ARTIFACT_SUBJECT_GIT_REF}"
    - tenant: openebs # storage
      configs: false
      tag: "${ARTIFACT_TAG}"
      environment: "${ENVIRONMENT}"
      artifactSubjectWorkflow: "${ARTIFACT_SUBJECT_WORKFLOW}"
      artifactSubjectGitRef: "${ARTIFACT_SUBJECT_GIT_REF}"
    - tenant: monitoring
      configs: true
      tag: "${ARTIFACT_TAG}"
      environment: "${ENVIRONMENT}"
      artifactSubjectWorkflow: "${ARTIFACT_SUBJECT_WORKFLOW}"
      artifactSubjectGitRef: "${ARTIFACT_SUBJECT_GIT_REF}"
      dependsOn:
        - name: external-secrets-configs
          namespace: external-secrets
        - name: openebs-controllers
          namespace: openebs
  resources:
    # FIXME: merge labels if present in d2-infra
    # components/monitoring/controllers/base/namespace.yaml
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << get inputs "namespace" | default inputs.tenant >>
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.tenant >>-controllers
        namespace: << get inputs "namespace" | default inputs.tenant >>
      spec:
        dependsOn: << get inputs "dependsOn" | default list | toYaml | nindent 4 >>
        targetNamespace: << get inputs "namespace" | default inputs.tenant >>
        serviceAccountName: flux
        interval: 30m
        retryInterval: 5m
        wait: true
        timeout: 5m
        sourceRef:
          kind: OCIRepository
          name: << inputs.tenant >>
        path: "./controllers/<< inputs.environment >>"
        prune: true
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: flux-runtime-env
            - kind: ConfigMap
              name: flux-runtime-info
    # TODO: optional / only if present
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.tenant >>-configs
        namespace: << get inputs "namespace" | default inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/reconcile: << if eq inputs.configs true >>enabled<< else >>disabled<< end >>
      spec:
        dependsOn:
          - name: << inputs.tenant >>-controllers
        targetNamespace: << get inputs "namespace" | default inputs.tenant >>
        serviceAccountName: flux
        interval: 30m
        retryInterval: 5m
        wait: true
        timeout: 5m
        sourceRef:
          kind: OCIRepository
          name: << inputs.tenant >>
        path: "./configs/<< inputs.environment >>"
        prune: true
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: flux-runtime-env
            - kind: ConfigMap
              name: flux-runtime-info

    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: flux-runtime-env
        namespace: << get inputs "namespace" | default inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/flux-runtime-env"
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: flux-runtime-info
        namespace: << get inputs "namespace" | default inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/flux-runtime-info"
        labels:
          reconcile.fluxcd.io/watch: Enabled
    - apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-auth
        namespace: << get inputs "namespace" | default inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/ghcr-auth"
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: flux
        namespace: << get inputs "namespace" | default inputs.tenant >>
      imagePullSecrets:
        - name: ghcr-auth
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: flux-infra-<< inputs.tenant >>
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: flux
          namespace: << get inputs "namespace" | default inputs.tenant >>
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: << inputs.tenant >>
        namespace: << get inputs "namespace" | default inputs.tenant >>
      spec:
        interval: 5m
        serviceAccountName: flux
        url: "oci://ghcr.io/1ab-io/d2-infra/<< inputs.tenant >>"
        ref:
          tag: << inputs.tag >>
        verify:
          provider: cosign
          matchOIDCIdentity:
            - issuer: ^https://token\.actions\.githubusercontent\.com$
              subject: ^https://github\.com/1ab-io/d2-infra/\.github/workflows/<< inputs.artifactSubjectWorkflow >>\.yaml@<< inputs.artifactSubjectGitRef >>$
    - apiVersion: v1
      kind: Secret
      metadata:
        name: bitwarden-tls-certs
        namespace: << get inputs "namespace" | default inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "cert-manager/bitwarden-tls-certs"
          fluxcd.controlplane.io/reconcile: << if eq inputs.tenant "external-secrets" >>enabled<< else >>disabled<< end >>
