name: e2e-staging

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]

jobs:
  e2e:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flux
        uses: controlplaneio-fluxcd/distribution/actions/setup@main
      - name: Setup Helm
        uses: fluxcd/pkg/actions/helm@main
      - name: Setup Kubernetes
        uses: helm/kind-action@main
        with:
          config: .github/kind.yaml
      - name: Bootstrap Flux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make bootstrap-staging
      - name: Verify cluster reconciliation
        run: make verify-cluster
      - name: Debug failure
        if: failure()
        run: make debug-cluster
