name: push-artifact

on:
  workflow_dispatch:

jobs:
  flux-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # for pushing
      id-token: write # for signing
    steps:
      - uses: actions/checkout@v4
      - uses: controlplaneio-fluxcd/distribution/actions/setup@push-action
      - uses: sigstore/cosign-installer@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: controlplaneio-fluxcd/distribution/actions/push@main
        id: push
        with:
          repository: ghcr.io/${{ github.repository }}
          path: "./"
          diff-tag: latest
      - if: steps.push.outputs.pushed == 'true'
        run: cosign sign --yes $DIGEST_URL
        env:
          DIGEST_URL: ${{ steps.push.outputs.digest-url }}
